server:
    port: 8082

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: account
  datasource:
    url: jdbc:h2:mem:testdb # Endpoint details which the application can connect to internal H2 database
    driver-class-name: org.h2.Driver
    username: sa # default name
    password: '' # default password
  h2:
    console:
      enabled: true # Enable H2 console --> Able to see table, column, row,.... in the browser.
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #
    show-sql: true # Print all sql query

# Spring doc property
springdoc:
  api-docs:
    path: /api-docs

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production1 APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}f181ae37da7f8fb5121dc15c9131026d6bb62e1ffd2c807e56519e2cf5bb444675dd86bf0ec57244e8e240ffbe1a93a8"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384


