server:
    port: 8082

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # default name
    password: root # default password
  jpa:
    show-sql: true # Print all sql query
  sql:
    init:
      mode: always

# Spring doc property
springdoc:
  api-docs:
    path: /api-docs

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}f181ae37da7f8fb5121dc15c9131026d6bb62e1ffd2c807e56519e2cf5bb444675dd86bf0ec57244e8e240ffbe1a93a8"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384


